#!/bin/bash
echo 'usage: ./bbf-rsync [DIR of Local BBF]'

Omega_M=(0.1 0.25 0.5 0.75 1.0)
Omega_DE=(0.0 0.25 0.5 0.75 1.0)

DE_type=(Lambda Quint Phantom)
fNL=(1000 -1000)
m_WDM=0.5
f_R0=-1e-04

DIR=$1; BBFdir=/home/PERSONALE/shared/BBF/DATA/BBF/

##---: Dark Energy suite
#for Omega_m in ${Omega_M[*]}; do
#for Omega_L in ${Omega_DE[*]}; do
#for type in ${DE_type[*]}; do
#
#model_ID=${type}_${Omega_m}-${Omega_L}
#modeldir=${BBFdir}/BBF_${model_ID}
#
#rsync -av --exclude 'ICs' bladerunner:${modeldir} ${DIR}
#done
#done
#done
#
##---: Dark Matter suite
#for Omega_m in ${Omega_M[*]}; do
#for Omega_L in ${Omega_DE[*]}; do
#
#model_ID=wDM_${m_WDM}-${Omega_m}-${Omega_L}
#modeldir=${BBFdir}/BBF_${model_ID}
#
#rsync -av --exclude 'ICs' bladerunner:${modeldir} ${DIR}
#done
#done
#
##---: PNG suite
#for Omega_m in ${Omega_M[*]}; do
#for Omega_L in ${Omega_DE[*]}; do
#for fnL in ${fNL[*]}; do
#
#model_ID=LocalPNG_${fnL}-${Omega_m}-${Omega_L}
#modeldir=${BBFdir}/BBF_${model_ID}
#
#rsync -av --exclude 'ICs' bladerunner:${modeldir} ${DIR}
#done
#done
#done

#---: Modified Gravity suite
for Omega_m in ${Omega_M[*]}; do
for Omega_L in ${Omega_DE[*]}; do

model_ID=MGfR_${f_R0}-${Omega_m}-${Omega_L}
modeldir=${BBFdir}/BBF_${model_ID}

rsync -av --exclude 'ICs' bladerunner:${modeldir} ${DIR}
done
done



