"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
#import matplotlib
#from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
import FileDialog
import Dialog
from setuptools import setup
from six.moves import tkinter_filedialog as FileDialog

import tkinter.filedialog, tkinter.messagebox

import os, sys
sys.setrecursionlimit(2000)

APP = ['gui.py']
APP_NAME = "BigBangFactory"
DATA_FILES = ['Omega_lambda.gif', 'Omega_m.gif', 'quit.gif', 'run.gif']
OPTIONS = {'iconfile': 'bbf_icon.icns', 'argv_emulation': True, 'packages': ['FileDialog', 'Dialog'],
            'excludes': ['matplotlib.afm', 'matplotlib.cbook', 'matplotlib.ft2font', 'matplotlib.rcParams', 'matplotlib.get_cachedir']}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    requires=['FileDialog', 'Dialog'],
    setup_requires=['py2app'],
)
